In [3]:
# Run this in a cell to downgrade chromadb
!pip install chromadb==0.4.24

Collecting chromadb==0.4.24
  Using cached chromadb-0.4.24-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: build>=1.0.3 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from chromadb==0.4.24) (1.3.0)
Requirement already satisfied: requests>=2.28 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from chromadb==0.4.24) (2.32.5)
Requirement already satisfied: pydantic>=1.9 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from chromadb==0.4.24) (2.11.10)
Collecting chroma-hnswlib==0.7.3 (from chromadb==0.4.24)
  Using cached chroma-hnswlib-0.7.3.tar.gz (31 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: fastapi>=0.95.2 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from chromadb==0.4.24) (0.120.4)
Requirement already satisfied: uvicorn>=0.18.3 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb==0.4.24) (0.35.0)
Requirement already satisfied: numpy>=1.22.5 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from chromadb==0.4.24) (2.3.3)
Requirement already satisfied: posthog>=2.4.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from chromadb==0.4.24) (5.4.0)
Requirement already satisfied: typing-extensions>=4.5.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from chromadb==0.4.24) (4.15.0)
Collecting pulsar-client>=3.1.0 (from chromadb==0.4.24)
  Using cached pulsar_client-3.8.0-cp313-cp313-win_amd64.whl.metadata (1.2 kB)
Requirement already satisfied: onnxruntime>=1.14.1 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from chromadb==0.4.24) (1.22.1)
Requirement already satisfied: opentelemetry-api>=1.2.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from chromadb==0.4.24) (1.37.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from chromadb==0.4.24) (1.37.0)
Collecting opentelemetry-instrumentation-fastapi>=0.41b0 (from chromadb==0.4.24)
  Using cached opentelemetry_instrumentation_fastapi-0.59b0-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from chromadb==0.4.24) (1.37.0)
Requirement already satisfied: tokenizers>=0.13.2 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from chromadb==0.4.24) (0.22.1)
Requirement already satisfied: pypika>=0.48.9 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from chromadb==0.4.24) (0.48.9)
Requirement already satisfied: tqdm>=4.65.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from chromadb==0.4.24) (4.67.1)
Requirement already satisfied: overrides>=7.3.1 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from chromadb==0.4.24) (7.7.0)
Requirement already satisfied: importlib-resources in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from chromadb==0.4.24) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from chromadb==0.4.24) (1.75.0)
Requirement already satisfied: bcrypt>=4.0.1 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from chromadb==0.4.24) (4.3.0)
Requirement already satisfied: typer>=0.9.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from chromadb==0.4.24) (0.17.5)
Requirement already satisfied: kubernetes>=28.1.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from chromadb==0.4.24) (33.1.0)
Requirement already satisfied: tenacity>=8.2.3 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from chromadb==0.4.24) (9.1.2)
Requirement already satisfied: PyYAML>=6.0.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from chromadb==0.4.24) (6.0.2)
Requirement already satisfied: mmh3>=4.0.1 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from chromadb==0.4.24) (5.2.0)
Requirement already satisfied: orjson>=3.9.12 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from chromadb==0.4.24) (3.11.3)
Requirement already satisfied: packaging>=19.1 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from build>=1.0.3->chromadb==0.4.24) (25.0)
Requirement already satisfied: pyproject_hooks in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from build>=1.0.3->chromadb==0.4.24) (1.2.0)
Requirement already satisfied: colorama in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from build>=1.0.3->chromadb==0.4.24) (0.4.6)
Requirement already satisfied: starlette<0.50.0,>=0.40.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from fastapi>=0.95.2->chromadb==0.4.24) (0.49.1)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from fastapi>=0.95.2->chromadb==0.4.24) (0.0.3)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from pydantic>=1.9->chromadb==0.4.24) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from pydantic>=1.9->chromadb==0.4.24) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from pydantic>=1.9->chromadb==0.4.24) (0.4.1)
Requirement already satisfied: anyio<5,>=3.6.2 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from starlette<0.50.0,>=0.40.0->fastapi>=0.95.2->chromadb==0.4.24) (4.10.0)
Requirement already satisfied: idna>=2.8 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from anyio<5,>=3.6.2->starlette<0.50.0,>=0.40.0->fastapi>=0.95.2->chromadb==0.4.24) (3.10)
Requirement already satisfied: sniffio>=1.1 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from anyio<5,>=3.6.2->starlette<0.50.0,>=0.40.0->fastapi>=0.95.2->chromadb==0.4.24) (1.3.1)
Requirement already satisfied: certifi>=14.05.14 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from kubernetes>=28.1.0->chromadb==0.4.24) (2025.10.5)
Requirement already satisfied: six>=1.9.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from kubernetes>=28.1.0->chromadb==0.4.24) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from kubernetes>=28.1.0->chromadb==0.4.24) (2.9.0.post0)
Requirement already satisfied: google-auth>=1.0.1 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from kubernetes>=28.1.0->chromadb==0.4.24) (2.40.3)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from kubernetes>=28.1.0->chromadb==0.4.24) (1.9.0)
Requirement already satisfied: requests-oauthlib in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from kubernetes>=28.1.0->chromadb==0.4.24) (2.0.0)
Requirement already satisfied: oauthlib>=3.2.2 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from kubernetes>=28.1.0->chromadb==0.4.24) (3.3.1)
Requirement already satisfied: urllib3>=1.24.2 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from kubernetes>=28.1.0->chromadb==0.4.24) (2.3.0)
Requirement already satisfied: durationpy>=0.7 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from kubernetes>=28.1.0->chromadb==0.4.24) (0.10)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb==0.4.24) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb==0.4.24) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb==0.4.24) (4.9.1)
Requirement already satisfied: pyasn1>=0.1.3 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from rsa<5,>=3.1.4->google-auth>=1.0.1->kubernetes>=28.1.0->chromadb==0.4.24) (0.6.1)
Requirement already satisfied: coloredlogs in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from onnxruntime>=1.14.1->chromadb==0.4.24) (15.0.1)
Requirement already satisfied: flatbuffers in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from onnxruntime>=1.14.1->chromadb==0.4.24) (25.2.10)
Requirement already satisfied: protobuf in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from onnxruntime>=1.14.1->chromadb==0.4.24) (6.32.1)
Requirement already satisfied: sympy in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from onnxruntime>=1.14.1->chromadb==0.4.24) (1.14.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from opentelemetry-api>=1.2.0->chromadb==0.4.24) (8.7.0)
Requirement already satisfied: zipp>=3.20 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb==0.4.24) (3.23.0)
Requirement already satisfied: googleapis-common-protos~=1.57 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb==0.4.24) (1.70.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.37.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb==0.4.24) (1.37.0)
Requirement already satisfied: opentelemetry-proto==1.37.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb==0.4.24) (1.37.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.58b0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from opentelemetry-sdk>=1.2.0->chromadb==0.4.24) (0.58b0)
Collecting opentelemetry-instrumentation-asgi==0.59b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb==0.4.24)
  Using cached opentelemetry_instrumentation_asgi-0.59b0-py3-none-any.whl.metadata (2.0 kB)
Collecting opentelemetry-instrumentation==0.59b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb==0.4.24)
  Using cached opentelemetry_instrumentation-0.59b0-py3-none-any.whl.metadata (7.1 kB)
INFO: pip is looking at multiple versions of opentelemetry-instrumentation-fastapi to determine which version is compatible with other requirements. This could take a while.
Collecting opentelemetry-instrumentation-fastapi>=0.41b0 (from chromadb==0.4.24)
  Using cached opentelemetry_instrumentation_fastapi-0.58b0-py3-none-any.whl.metadata (2.2 kB)
Collecting opentelemetry-instrumentation-asgi==0.58b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb==0.4.24)
  Using cached opentelemetry_instrumentation_asgi-0.58b0-py3-none-any.whl.metadata (2.0 kB)
Collecting opentelemetry-instrumentation==0.58b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb==0.4.24)
  Using cached opentelemetry_instrumentation-0.58b0-py3-none-any.whl.metadata (7.1 kB)
Collecting opentelemetry-util-http==0.58b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb==0.4.24)
  Using cached opentelemetry_util_http-0.58b0-py3-none-any.whl.metadata (2.6 kB)
Collecting wrapt<2.0.0,>=1.0.0 (from opentelemetry-instrumentation==0.58b0->opentelemetry-instrumentation-fastapi>=0.41b0->chromadb==0.4.24)
  Using cached wrapt-1.17.3-cp313-cp313-win_amd64.whl.metadata (6.5 kB)
Collecting asgiref~=3.0 (from opentelemetry-instrumentation-asgi==0.58b0->opentelemetry-instrumentation-fastapi>=0.41b0->chromadb==0.4.24)
  Using cached asgiref-3.10.0-py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: backoff>=1.10.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from posthog>=2.4.0->chromadb==0.4.24) (2.2.1)
Requirement already satisfied: distro>=1.5.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from posthog>=2.4.0->chromadb==0.4.24) (1.9.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from requests>=2.28->chromadb==0.4.24) (3.4.3)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from tokenizers>=0.13.2->chromadb==0.4.24) (0.35.0)
Requirement already satisfied: filelock in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb==0.4.24) (3.19.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb==0.4.24) (2025.10.0)
Requirement already satisfied: click<8.3.0,>=8.0.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from typer>=0.9.0->chromadb==0.4.24) (8.2.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from typer>=0.9.0->chromadb==0.4.24) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from typer>=0.9.0->chromadb==0.4.24) (14.1.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from rich>=10.11.0->typer>=0.9.0->chromadb==0.4.24) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from rich>=10.11.0->typer>=0.9.0->chromadb==0.4.24) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer>=0.9.0->chromadb==0.4.24) (0.1.2)
Requirement already satisfied: h11>=0.8 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from uvicorn>=0.18.3->uvicorn[standard]>=0.18.3->chromadb==0.4.24) (0.16.0)
Requirement already satisfied: httptools>=0.6.3 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb==0.4.24) (0.6.4)
Requirement already satisfied: python-dotenv>=0.13 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb==0.4.24) (1.1.1)
Requirement already satisfied: watchfiles>=0.13 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb==0.4.24) (1.1.0)
Requirement already satisfied: websockets>=10.4 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb==0.4.24) (15.0.1)
Requirement already satisfied: humanfriendly>=9.1 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from coloredlogs->onnxruntime>=1.14.1->chromadb==0.4.24) (10.0)
Requirement already satisfied: pyreadline3 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime>=1.14.1->chromadb==0.4.24) (3.5.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\anyor\pycharmprojects\book-recommender\.venv\lib\site-packages (from sympy->onnxruntime>=1.14.1->chromadb==0.4.24) (1.3.0)
Using cached chromadb-0.4.24-py3-none-any.whl (525 kB)
Using cached opentelemetry_instrumentation_fastapi-0.58b0-py3-none-any.whl (13 kB)
Using cached opentelemetry_instrumentation-0.58b0-py3-none-any.whl (33 kB)
Using cached opentelemetry_instrumentation_asgi-0.58b0-py3-none-any.whl (16 kB)
Using cached opentelemetry_util_http-0.58b0-py3-none-any.whl (7.7 kB)
Using cached asgiref-3.10.0-py3-none-any.whl (24 kB)
Using cached wrapt-1.17.3-cp313-cp313-win_amd64.whl (38 kB)
Using cached pulsar_client-3.8.0-cp313-cp313-win_amd64.whl (3.7 MB)
Building wheels for collected packages: chroma-hnswlib
  Building wheel for chroma-hnswlib (pyproject.toml): started
  Building wheel for chroma-hnswlib (pyproject.toml): finished with status 'error'
Failed to build chroma-hnswlib

  error: subprocess-exited-with-error

  × Building wheel for chroma-hnswlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'hnswlib' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for chroma-hnswlib

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Failed to build installable wheels for some pyproject.toml based projects (chroma-hnswlib)

In [4]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma

In [5]:
from dotenv import load_dotenv

load_dotenv()

True

In [6]:
import pandas as pd

books = pd.read_csv("books_cleaned.csv")

In [7]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...

In [8]:
books["tagged_description"].to_string("tagged_description.txt", index=False)

In [9]:
raw_documents = TextLoader("tagged_description.txt", encoding='utf-8').load()
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0, separator="\n")
documents = text_splitter.split_documents(raw_documents)

In [11]:
from langchain.schema import Document

# Create documents directly from the DataFrame - one document per book
documents = []
for _, row in books.iterrows():
    doc = Document(
        page_content=row['description'],  # Just the description, not ISBN
        metadata={
            'isbn13': int(row['isbn13']),  # Store ISBN as metadata
            'title': row['title'],
            'authors': row['authors'],
            'categories': row['categories']
        }
    )
    documents.append(doc)

print(f"Created {len(documents)} documents")

Created 5197 documents

In [12]:
db_books = Chroma.from_documents(
    documents,
    embedding=OpenAIEmbeddings()) # Try 'embedding' explicitly, just in case the function expects this)

In [13]:
query = "A book to teach children about nature"
docs = db_books.similarity_search(query, k = 10)
docs

[Document(id='7ff788ca-78a1-449c-8a19-db3f1e805886', metadata={'categories': 'Juvenile Fiction', 'authors': 'Marilyn Singer;Julie Aigner-Clark', 'title': 'Baby Einstein: Neighborhood Animals', 'isbn13': 9780786808069}, page_content='Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience.'),
 Document(id='5438169e-93b5-4102-b014-659f8a073a56', metadata={'categories': 'Juvenile Fiction', 'title': 'Baby Einstein: Babies', 'isbn13': 9780786808380, 'authors': 'Julie Aigner-Clark'}, page_content="Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."),
 Document(id='517a5089-9584-47d8-b605-42bdfe8616b3', metadata={'categories': 'Animal sounds', 'isbn13': 9780689861130, 'title': 'Moo, Baa, la la La!', 'authors': 'Sandra Boynton'}, page_content="Children will love joining in and imitating the animal noises and sounds in this big, bold board book format, illustrated with Sandra Boynton's seriously silly signature animals."),
 Document(id='7fee5469-012c-4859-8577-5f871e212995', metadata={'categories': 'Juvenile Fiction', 'title': 'Baby Einstein: Dogs', 'isbn13': 9780786808397, 'authors': 'Julie Aigner-Clark'}, page_content="Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."),
 Document(id='8d5017de-e126-464e-9f2c-56e977f9522f', metadata={'categories': 'Juvenile Fiction', 'authors': 'Julie Aigner-Clark', 'title': 'Baby Einstein: Birds', 'isbn13': 9780786808373}, page_content="Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects."),
 Document(id='d1bd4e6e-c480-40f5-b50b-b0df77882b85', metadata={'title': 'The Big Box', 'authors': 'Toni Morrison;Slade Morrison', 'categories': 'Juvenile Fiction', 'isbn13': 9780786812912}, page_content='In her first illustrated book for children, the Pulitzer Prize–winning author Toni Morrison introduces three feisty children who show grown-ups what it really means to be a kid.'),
 Document(id='69af2a71-99ff-45d4-99a5-7cab324fec9f', metadata={'title': 'Baby Einstein: What Does Violet See? Raindrops and Puddles', 'authors': 'Julie Aigner-Clark', 'isbn13': 9780786808717, 'categories': 'Juvenile Fiction'}, page_content='A very special puddle sets Violet the mouse off on her latest nature discovery. It is through this puddle that Violet observes the effect rain has on the world around her. A Mylar puddle on the last page offers children a chance to see their reflection in a puddle, just like Violet!'),
 Document(id='fe2706e1-b4db-4f60-9107-d68e863a4c9a', metadata={'title': 'The Very Hungry Caterpillar', 'isbn13': 9780241003008, 'authors': 'Eric Carle', 'categories': 'Babytime resource'}, page_content="Eric Carle's children's classic is the story of a very small and very hungry caterpillar who manages to nibble his way through the pages of this enchanting book."),
 Document(id='9746023e-1623-47bb-9da3-bdf53ea19ca9', metadata={'title': 'The Sense of Wonder', 'categories': 'Nature', 'isbn13': 9780067575208, 'authors': 'Rachel Carson'}, page_content='First published more than three decades ago, this reissue of Rachel Carson\'s award-winning classic brings her unique vision to a new generation of readers. Stunning new photographs by Nick Kelsh beautifully complement Carson\'s intimate account of adventures with her young nephew, Roger, as they enjoy walks along the rocky coast of Maine and through dense forests and open fields, observing wildlife, strange plants, moonlight and storm clouds, and listening to the "living music" of insects in the underbrush. "If a child is to keep alive his inborn sense of wonder." Writes Carson, "he needs the companionship of at least one adult who can share it, rediscovering with him the joy, excitement and mystery of the world we live in." The Sense of Wonder is a refreshing antidote to indifference and a guide to capturing the simple power of discovery that Carson views as essential to life. In her insightful new introduction, Linda Lear remembers Rachel Carson\'s groundbreaking achievements in the context of the legendary environmentalist\'s personal commitment to introducing young and old to the miracles of nature. Kelsh\'s lush photographs inspire sensual, tactile reactions: masses of leaves floating in a puddle are just waiting to be scooped up and examined more closely. An image of a narrow path through the trees evokes the earthy scent of the woods after a summer rain. Close-ups of mosses and miniature lichen fantasy-lands will spark innocent\'as well as more jaded\'imaginations. Like a curious child studying things underfoot and within reach, Kelsh\'s camera is drawn to patterns in nature that too often elude hurried adults\'a stand of beech trees in the springtime, patches of melting snow and the ripples from a pebble tossed into a slow-moving stream. The Sense of Wonder is a timeless volume that will be passed on from children to grandchildren, as treasured as the memory of an early-morning walk when the song of a whippoorwill was heard as if for the first time.'),
 Document(id='ab4e26c5-c7c4-4eaa-9bfc-abeeb29fbd4d', metadata={'title': "The Little Big Book for God's Children", 'categories': 'Religion', 'authors': 'Lena Tabori;Alice Wong', 'isbn13': 9780941807555}, page_content="THE LITTLE BIG BOOK FOR GOD'S CHILDREN is a wonderful resource for parents looking to introduce their children to the wisdom and beauty of Christian faith. Illustrated with early twentieth-century art from artists such as Jessie Wilcox Smith, Ellen H. Clapsaddle, and Maud and Miska Petersham, this Little Big Book presents selected bible stories, parables, and verses; poems and prayers; excerpts and fables; songs and hymns; and activities - all collected in one delightful volume. A celebration of God's enduring message of love, GOD'S CHILDREN is sure to provide an endless wellspring of inspiration and hope.")]

In [14]:
books[books["isbn13"] == docs[0].metadata['isbn13']]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,Baby Einstein: Neighborhood Animals,9780786808069 Children will discover the excit...

In [15]:
def retrieve_semantic_recommendations(
        query: str,
        top_k: int = 10,
) -> pd.DataFrame:
    # Perform similarity search
    recs = db_books.similarity_search(query, k=top_k)

    # Extract ISBNs from metadata
    books_list = [rec.metadata['isbn13'] for rec in recs]

    # Filter books and preserve order
    result_books = books[books["isbn13"].isin(books_list)]

    # Maintain the ranking order from similarity search
    isbn_to_rank = {isbn: i for i, isbn in enumerate(books_list)}
    result_books = result_books.copy()
    result_books['rank'] = result_books['isbn13'].map(isbn_to_rank)
    result_books = result_books.sort_values('rank').drop('rank', axis=1)

    return result_books.head(top_k)

In [16]:
retrieve_semantic_recommendations("A book to teach children about science")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,Baby Einstein: Neighborhood Animals,9780786808069 Children will discover the excit...
2887,9780618056736,0618056734,Unweaving the Rainbow,Richard Dawkins,Science,http://books.google.com/books/content?id=GWj0q...,"Offers an assessment of what science is, how i...",2000.0,4.02,352.0,9168.0,"Unweaving the Rainbow: Science, Delusion and t...",9780618056736 Offers an assessment of what sci...
1351,9780316281331,0316281336,"The World Treasury of Physics, Astronomy, and ...",Timothy Ferris;Clifton Fadiman,Education,http://books.google.com/books/content?id=zryXG...,The writings of more than 60 authors including...,1993.0,4.12,859.0,361.0,"The World Treasury of Physics, Astronomy, and ...",9780316281331 The writings of more than 60 aut...
2658,9780553103748,0553103741,The Illustrated a Brief History of Time,Stephen Hawking,Science,http://books.google.com/books/content?id=wDr8u...,"An illustrated, large-format edition of the be...",1996.0,4.16,256.0,750.0,The Illustrated a Brief History of Time,"9780553103748 An illustrated, large-format edi..."
2477,9780471265184,0471265187,Astronomy,Dinah L. Moché,Science,http://books.google.com/books/content?id=vBFuF...,"""A lively, up-to-date account of the basic pri...",2004.0,3.89,343.0,109.0,Astronomy: A Self-Teaching Guide,"9780471265184 ""A lively, up-to-date account of..."
549,9780131871656,013187165X,Astronomy,Eric Chaisson;Stephen McMillan,Mathematics,http://books.google.com/books/content?id=1O00A...,This introduction to astronomy features an exc...,2006.0,3.85,499.0,153.0,Astronomy: a beginner's guide to the universe,9780131871656 This introduction to astronomy f...
3767,9780786849734,0786849738,Disney's Little Einsteins: Galactic Goodnight,Susan Ring,Juvenile Fiction,http://books.google.com/books/content?id=Nm3N3...,"The Little Einsteins, equipped with their came...",2006.0,4.50,20.0,10.0,Disney's Little Einsteins: Galactic Goodnight,"9780786849734 The Little Einsteins, equipped w..."
4383,9781400077809,140007780X,Einstein's Dreams,Alan P. Lightman,Fiction,http://books.google.com/books/content?id=1oSGm...,Young Albert Einstein's dreams are imagined in...,1993.0,4.07,144.0,24345.0,Einstein's Dreams,9781400077809 Young Albert Einstein's dreams a...
2409,9780451456816,0451456815,Not of Woman Born,Constance Ash;Robert A. Silverberg,Fiction,http://books.google.com/books/content?id=nOEIA...,A collection of stories that detail modern sci...,1999.0,3.80,288.0,59.0,Not of Woman Born,9780451456816 A collection of stories that det...
3579,9780762427321,0762427329,The Illustrated on the Shoulders of Giants,Stephen W. Hawking,Science,http://books.google.com/books/content?id=r1y3P...,Hawking's revolutionary look at the scientific...,2005.0,4.20,256.0,4014.0,The Illustrated on the Shoulders of Giants: Th...,9780762427321 Hawking's revolutionary look at ...